### ISSUE TITLE
Bug in shrink_letsencrypt_cert(). `list.remove(x): x not in list`

### ISSUE THREAD

**Issue by larssb** [larssb/LetsEncryptIT#1]
HAPPENS:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/letsencryptit/shrink_letsencrypt_cert.py", line 76, in shrink_letsencrypt_cert
    certificateDomainsSplitted.remove('%s' % domain)
ValueError: list.remove(x): x not in list
command terminated with exit code 1
```

EXPECTED:

An error should not be thrown if a specified domain in the `domains` argument does not exist on the certificate

**Comment by larssb** [comment]
Fixed. With a simple try/catch ... see [this line in the commit](https://github.com/larssb/LetsEncryptIT/blob/4ca351b6b3c91a27e5e6b725a96dfad3fd4d6430/letsencryptit/shrink_letsencrypt_cert.py#L77)
